### ISSUE TITLE
running build locally errors

### ISSUE THREAD

**Issue by anotherrohit** [vymalo/keycloak-webhook#24]
## Summary

I get the following error deploying the build on my keycloak local instance. Any pointers, I deployed the jar from the code using gradlew jar and copied the jar to the providers folder of my keycloak26 instance, on starting up keyclaok I get the following error

C:\Users\Downloads\keycloak-26.0.1\keycloak-26.0.1\bin>kc.bat build --verbose
Updating the configuration and installing your custom providers, if any. Please wait.
SLF4J: The requested version 2.0.6 by your slf4j binding is not compatible with [1.6, 1.7]
SLF4J: See http://www.slf4j.org/codes.html#version_mismatch for further details.
The DelayedHandler was closed before any children handlers were configured. Messages will be written to stderr.
2024-11-17 14:27:34,284 DEBUG [org.jboss.logging] (main) Logging Provider: org.jboss.logging.JBossLogManagerProvider

2024-11-17 14:27:34,899 DEBUG [io.smallrye.config] (main) SRCFG01006: Loaded ConfigSource io.smallrye.config.ConfigSourceContext$ConfigSourceContextConfigSource with ordinal 2147483647

2024-11-17 14:27:34,899 DEBUG [io.smallrye.config] (main) SRCFG01006: Loaded ConfigSource DefaultValuesConfigSource with ordinal -2147483648

2024-11-17 14:27:34,910 DEBUG [io.smallrye.config] (main) SRCFG01006: Loaded ConfigSource io.smallrye.config.ConfigSourceContext$ConfigSourceContextConfigSource with ordinal 2147483647

2024-11-17 14:27:34,910 DEBUG [io.smallrye.config] (main) SRCFG01006: Loaded ConfigSource DefaultValuesConfigSource with ordinal -2147483648

2024-11-17 14:27:34,910 DEBUG [io.smallrye.config] (main) SRCFG01006: Loaded ConfigSource PropertiesConfigSource[source=CliConfigSource] with ordinal 600

2024-11-17 14:27:34,910 DEBUG [io.smallrye.config] (main) SRCFG01006: Loaded ConfigSource KcEnvVarConfigSource with ordinal 500

2024-11-17 14:27:34,910 DEBUG [io.smallrye.config] (main) SRCFG01006: Loaded ConfigSource QuarkusProperties with ordinal 450

2024-11-17 14:27:34,910 DEBUG [io.smallrye.config] (main) SRCFG01006: Loaded ConfigSource file:/C:/Users/nayak/Downloads/keycloak-26.0.1/keycloak-26.0.1/bin/../conf/keycloak.conf with ordinal 450

2024-11-17 14:27:34,910 DEBUG [io.smallrye.config] (main) SRCFG01006: Loaded ConfigSource SysPropConfigSource with ordinal 400

2024-11-17 14:27:34,910 DEBUG [io.smallrye.config] (main) SRCFG01006: Loaded ConfigSource EnvConfigSource with ordinal 300

2024-11-17 14:27:34,910 DEBUG [io.smallrye.config] (main) SRCFG01006: Loaded ConfigSource PropertiesConfigSource[source=jar:file:///C:/Users/nayak/Downloads/keycloak-26.0.1/keycloak-26.0.1/lib/app/keycloak.jar!/application.properties] with ordinal 250

2024-11-17 14:27:34,910 DEBUG [io.smallrye.config] (main) SRCFG01006: Loaded ConfigSource PropertiesConfigSource[source=jar:file:///C:/Users/nayak/Downloads/keycloak-26.0.1/keycloak-26.0.1/lib/lib/main/org.keycloak.keycloak-quarkus-server-26.0.1.jar!/application.properties] with ordinal 250

2024-11-17 14:27:34,910 DEBUG [io.smallrye.config] (main) SRCFG01006: Loaded ConfigSource PersistedConfigSource with ordinal 200

2024-11-17 14:27:34,910 DEBUG [io.smallrye.config] (main) SRCFG01006: Loaded ConfigSource jar:file:///C:/Users/nayak/Downloads/keycloak-26.0.1/keycloak-26.0.1/lib/lib/main/org.keycloak.keycloak-quarkus-server-26.0.1.jar!/META-INF/keycloak.conf with ordinal 150

2024-11-17 14:27:34,910 DEBUG [io.smallrye.config] (main) SRCFG01006: Loaded ConfigSource DefaultValuesConfigSource with ordinal -2147483648

2024-11-17 14:27:34,954 DEBUG [org.keycloak.quarkus.runtime.configuration.mappers.PropertyMappers] (main) Duplicated mappers for key 'kc.dir'. Used the first found.

2024-11-17 14:27:34,954 DEBUG [org.keycloak.quarkus.runtime.configuration.mappers.PropertyMappers] (main) Duplicated mappers for key 'kc.dir'. Used the first found.

2024-11-17 14:27:34,954 DEBUG [org.keycloak.quarkus.runtime.configuration.mappers.PropertyMappers] (main) Duplicated mappers for key 'kc.dir'. Used the first found.

2024-11-17 14:27:34,955 DEBUG [org.keycloak.quarkus.runtime.configuration.mappers.PropertyMappers] (main) Duplicated mappers for key 'kc.dir'. Used the first found.

2024-11-17 14:27:34,955 DEBUG [org.keycloak.quarkus.runtime.configuration.mappers.PropertyMappers] (main) Duplicated mappers for key 'kc.dir'. Used the first found.

2024-11-17 14:27:34,990 TRACE [java.io.serialization] (main) Builtin factory: null -> new: null

2024-11-17 14:27:35,197 TRACE [java.io.serialization] (main) Builtin factory: null -> new: null

ERROR: Failed to run 'build' command.
Error details:
java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:208)
        at java.base/java.util.ImmutableCollections$List12.<init>(ImmutableCollections.java:556)
        at java.base/java.util.List.of(List.java:812)
        at io.quarkus.paths.OpenContainerPathTree.getRoots(OpenContainerPathTree.java:96)
        at io.quarkus.paths.SharedArchivePathTree$CallerOpenPathTree.getRoots(SharedArchivePathTree.java:142)
        at io.quarkus.bootstrap.classloading.PathTreeClassPathElement.toString(PathTreeClassPathElement.java:214)
        at java.base/java.util.Formatter$FormatSpecifier.printString(Formatter.java:3056)
        at java.base/java.util.Formatter$FormatSpecifier.print(Formatter.java:2933)
        at java.base/java.util.Formatter.format(Formatter.java:2689)
        at java.base/java.util.Formatter.format(Formatter.java:2625)
        at java.base/java.lang.String.format(String.java:4147)
        at org.jboss.logmanager.ExtFormatter.formatMessagePrintf(ExtFormatter.java:144)
        at org.jboss.logmanager.ExtFormatter.formatMessage(ExtFormatter.java:91)
        at org.jboss.logmanager.formatters.Formatters$16.renderRaw(Formatters.java:832)
        at org.jboss.logmanager.formatters.Formatters$JustifyingFormatStep.render(Formatters.java:227)
        at org.jboss.logmanager.formatters.MultistepFormatter.format(MultistepFormatter.java:90)
        at org.jboss.logmanager.ExtFormatter.format(ExtFormatter.java:58)
        at io.quarkus.bootstrap.logging.QuarkusDelayedHandler.close(QuarkusDelayedHandler.java:157)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:35)
        at org.keycloak.quarkus.runtime.cli.command.Build.run(Build.java:82)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2030)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
        at picocli.CommandLine.execute(CommandLine.java:2174)
        at org.keycloak.quarkus.runtime.cli.Picocli.run(Picocli.java:147)
        at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:135)
        at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:106)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:62)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:33)

**Comment by stephane-segning** [comment]
In version [0.8.2](https://github.com/vymalo/keycloak-webhook/releases/tag/v0.8.2) this issue is fixed.
